# -*- coding: UTF-8 -*-

def _():
    import sys, os
    feflow_root = os.environ['FEFLOW72_ROOT']
    if feflow_root != '':
        sys.path.append(feflow_root + 'bin64')
    #		if sys.version_info > (3, 0):
    #			sys.path.append(feflow_root+'python/pyscriptlib37.zip')
    #		else:
    #			sys.path.append(feflow_root+'python/pyscriptlib27.zip')
    if sys.platform == 'cli':
        import clr
        clr.AddReference('IronPython.Feflow72')


_()
del _

import sys

if sys.platform == 'cli':
    from feflow import *


    def loadDocument(f):
        return PyFeflowKernel.loadDocument(f)
else:
    if sys.version_info > (3, 0):
        from ifm37 import *
        from ifm27 import loadDocument as _loadDocument
    else:
        from ifm27 import *
        from ifm27 import loadDocument as _loadDocument


    def loadDocument(f):
        return doc_contrib(f)


    class doc_contrib():
        """
        Contributors IfmDocument class.
        This class loads the original IfmDocument class and adds the contributors methods.
        DO NOT EDIT THIS FILE!!
        """

        def __init__(self, filename):
            # load document as standard IFM object and transfer all attributes to contributors IFM object
            self.pdoc = _loadDocument(filename)
            for item in dir(self.pdoc):
                self.__dict__[item] = self.pdoc.__getattribute__(item)

            # import contributors library
            import contrib_lib
            self.c = contrib_lib.IfmContrib(self)
